Repository GlueOps/slackbot-developer-workspaces, pull requests merged in 2024-12, with the labels that each got.

#101 fix: server description and tailscale timeout
  command-handler/src/util/libvirt/libvirt-server.js
Labels: include-in-release-notes, patch, Review effort [1-5]: 2

#102 fix: server description json
  command-handler/src/util/libvirt/libvirt-server.js
Labels: Review effort [1-5]: 1, include-in-release-notes, patch

#103 feat: adding tailscale notes
  README.md
Labels: enhancement, Review effort [1-5]: 1, include-in-release-notes, patch, minor

#108 chore update docs
  README.md
  bot/example.env
Labels: Review effort [1-5]: 1, include-in-release-notes, patch
