Repository GlueOps/slackbot-developer-workspaces, pull requests merged in 2024-10, with the labels that each got.

#27 feat: adding regions
  bot/example.env
  command-handler/src/cmd-handler/buttons.js
  command-handler/src/commands/vm.js
  command-handler/src/util/aws/aws-server.js
  command-handler/src/util/aws/get-aws-images.js
  command-handler/src/util/aws/get-instances.js
  command-handler/src/util/aws/get-security-groups.js
  command-handler/src/util/hetzner/hetzner-servers.js
Labels: enhancement, include-in-release-notes, patch, minor, Review effort [1-5]: 4

#31 fix: chage user format
  command-handler/src/util/format-user.js
Labels: include-in-release-notes, patch, Review effort [1-5]: 2

#34 fix: get subnets from aws
  command-handler/src/util/aws/aws-server.js
  command-handler/src/util/aws/get-subnets.js
Labels: include-in-release-notes, patch, bug fix, Review effort [1-5]: 2

#35 fix: change storage for aws
  command-handler/src/util/aws/aws-server.js
Labels: Review effort [1-5]: 1, include-in-release-notes, patch

#37 feat: add button builder and pull tailscale code out
  command-handler/src/commands/vm.js
  command-handler/src/util/aws/aws-server.js
  command-handler/src/util/button-builder.js
  command-handler/src/util/hetzner/hetzner-servers.js
  command-handler/src/util/tailscale/get-devices-info.js
  command-handler/src/util/tailscale/tailscale.js
Labels: enhancement, Review effort [1-5]: 3, include-in-release-notes, patch, minor

#43 fix(deps): update dependency express to v4.21.1
  server/package-lock.json
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, dependencies, auto-update

#41 fix(deps): update dependency winston to v3.15.0
  command-handler/package-lock.json
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, dependencies, auto-update

#40 fix(deps): update dependency @aws-sdk/client-ec2 to v3.666.0
  command-handler/package-lock.json
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, auto-update

#39 chore(deps): update actions/checkout digest to eef6144
  .github/workflows/image.yml
Labels: Review effort [1-5]: 1, include-in-release-notes, dependencies, auto-update

#44 fix(deps): update dependency @aws-sdk/client-ec2 to v3.667.0
  command-handler/package-lock.json
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, dependencies, auto-update

#45 fix: axios error e.response undefined
  command-handler/src/util/axios-error-handler.js
  command-handler/src/util/hetzner/hetzner-servers.js
Labels: include-in-release-notes, patch, bug fix, Review effort [1-5]: 2

#49 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync
